// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyqqoychqsxnqceahpsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5cXFveWNocXN4bnFjZWFocHNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTM3MjYsImV4cCI6MjA2Mjc4OTcyNn0.8f0-YMgehWgNTWmroypqq3DA504w1ekbqboLsBvMJfc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);